SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE IF NOT EXISTS `agenda` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `agenda`;

CREATE TABLE IF NOT EXISTS `contactos` (
  `ID` int(11) NOT NULL,
  `NOMBRE` varchar(100) NOT NULL,
  `DIRECCION` varchar(150) NOT NULL,
  `EMAIL` varchar(150) NOT NULL,
  `MOVIL` varchar(20) NOT NULL,
  `FIJO` varchar(20) NOT NULL,
  `GIRO` varchar(20) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

INSERT INTO `contactos` VALUES(1, 'Profesor Jirafales', 'Enrique segobiano # 21 ', 'eacherfirafa@hotmail.com', '52 1 3232323232', '12 36 54 78', 'profecional');
INSERT INTO `contactos` VALUES(2, 'Jaime Urrutia', 'Av. ALOPECIA #478B', 'urruja@aol.com', '(48) 45781236', '48 1 3157852412', 'PERSONAl');


ALTER TABLE `contactos`
  ADD PRIMARY KEY (`ID`);


ALTER TABLE `contactos`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=3;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
